// <auto-generated />
using System;
using Kitenest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kitenest.Migrations
{
    [DbContext(typeof(KitenestDbContext))]
    [Migration("20190119223947_ValidatorsTestMigration")]
    partial class ValidatorsTestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kitenest.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Kitenest.Models.Continent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Continentid");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Continentid");

                    b.ToTable("Continent");
                });

            modelBuilder.Entity("Kitenest.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Continentid");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Continentid");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Kitenest.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int?>("Cityid");

                    b.Property<int>("Continent_id");

                    b.Property<string>("Country");

                    b.Property<int?>("CountryId");

                    b.Property<int>("Mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<int?>("SchoolId");

                    b.HasKey("Id");

                    b.HasIndex("Cityid");

                    b.HasIndex("Continent_id");

                    b.HasIndex("CountryId");

                    b.HasIndex("SchoolId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Kitenest.Models.SchoolTime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("closeHour");

                    b.Property<DateTime>("openHour");

                    b.Property<DateTime>("workingFrom");

                    b.Property<DateTime>("workingTo");

                    b.HasKey("id");

                    b.ToTable("SchoolTime");
                });

            modelBuilder.Entity("Kitenest.Models.City", b =>
                {
                    b.HasOne("Kitenest.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Kitenest.Models.Continent", b =>
                {
                    b.HasOne("Kitenest.Models.Continent")
                        .WithMany("getContinents")
                        .HasForeignKey("Continentid");
                });

            modelBuilder.Entity("Kitenest.Models.Country", b =>
                {
                    b.HasOne("Kitenest.Models.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("Continentid");
                });

            modelBuilder.Entity("Kitenest.Models.School", b =>
                {
                    b.HasOne("Kitenest.Models.City")
                        .WithMany("Schools")
                        .HasForeignKey("Cityid");

                    b.HasOne("Kitenest.Models.Continent", "Continent")
                        .WithMany("Schools")
                        .HasForeignKey("Continent_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kitenest.Models.Country")
                        .WithMany("Schools")
                        .HasForeignKey("CountryId");

                    b.HasOne("Kitenest.Models.School")
                        .WithMany("getSchools")
                        .HasForeignKey("SchoolId");
                });
#pragma warning restore 612, 618
        }
    }
}
